name: Avaliar Modelo

on:
  push:
    paths:
      - 'models/test_models/main.py'
      - 'models/saved_models/modelo_soja.h5'
      - 'data/sample_validation'
      - '.github/workflows/validate_model.yml'
  workflow_dispatch:  # permite rodar manualmente.

jobs:
  avaliar:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout do repositÃ³rio
        uses: actions/checkout@v4

      - name: ğŸ Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: ğŸ“¦ Instalar dependÃªncias
        run: pip install -r requirements.txt

      - name: ğŸš€ Rodar script de avaliaÃ§Ã£o
        run: |
          python avaliador.py \
            --model-path models/saved_models/modelo_soja.h5 \
            --dataset-dir data/sample_validation \
            --output-dir models/test_models/reports

      - name: ğŸ“ Fazer upload do relatÃ³rio
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-classificacao
          path: reports/*.html
